// const url = 'https://api.thenewsapi.com/v1/news/top?api_token=mytoken'

// async function getData() {
//     const response = await fetch(url)
//     const data = await response.json()
//     console.log(data)
// }

// getData()

//------------------------------------

// const url = 'https://api.spotify.com/v1/artists/0k17h0D3J5VfsdmQ1iZtE8'

// async function getData() {
//     const request = new Request(url, {
//         headers: {
//             'Authorization': 'Bearer mytoken'
//         }
//     })
//     const response = await fetch(request)
//     const data = await response.json()
//     console.log(data)
// }

// getData()

//------------------------------------

const url = 'https://api.spotify.com/v1/artists/autogenerated'

const request = new Request(url, {
    headers: {
        'Authorization': 'Bearer 123'
    }
})

async function getData() {
    try {
        const response = await fetch(request)
        const data = await response.json()
        if (response.status !== 200) {
            console.log('Success', data)
        } else {
            console.log('Server Error', data.error.message)
        }
    } catch (error) {
        console.log('Fetch Error', error)
    }
}

getData()